### PR TITLE
fixes pkp/healthSciences/issues/220

### PR DESCRIPTION
**Pull request by AndrewGearhart**
fixes https://github.com/pkp/healthSciences/issues/220

### CODE REVIEW

**Comment by AndrewGearhart** [comment]
Well... this is disappointing.

**Comment by Vitaliy-1** [comment]
The error is unlikely related to this PR. I'll take a look

**Comment by Vitaliy-1** [comment]
There is an issue in the [OJS main branch](https://github.com/pkp/pkp-lib/issues/8263) which prevents automatic tests from successful execution for the theme; I've tested it manually. Thanks!

**Comment by AndrewGearhart** [comment]
Thank you so much @Vitaliy-1 ! 🍻

**Pull request merged**
