### PR TITLE
Registration form, updated tag-it init to retain reviewer interests when submit validation fails

### PR DESCRIPTION
**Pull request by ViRuSTriNiTy**
see #173, solution adopted from default theme

### CODE REVIEW

**Comment by ViRuSTriNiTy** [comment]
PR ready

**Comment by NateWr** [comment]
@ViRuSTriNiTy can you file an issue and link to this PR? We'll be doing some edits to this and other themes over the next month in preparation for v3.2 and I can test and merge this then. The issue will ensure I don't miss it.

**Comment by ViRuSTriNiTy** [comment]
@NateWr Done

**Comment by Vitaliy-1** [comment]
Thanks!

**Pull request merged**
