### PR TITLE
Fix tagit results showing a div at bottom of page #152

### PR DESCRIPTION
**Pull request by thinkbulecount2**
From Issue #152

### CODE REVIEW

**Comment by Vitaliy-1** [comment]
Thanks @thinkbulecount2,

Hmm, `No search results` appears for me under the div with `ui-helper-hidden-accessible` class. I would check the JQuery documentation on this if there is any, in particular, the purpose. Yeah, most probably we should hide it with absolute positioning.

**Comment by thinkbulecount2** [comment]
Thanks, @Vitaliy-1! In the default theme I did some changes to `ui-helper-hidden-accessible` so I will probably try to see how I can do the same for this theme. Thanks!!

**Comment by NateWr** [comment]
@thinkbulecount2 the CSS code will probably be identical.

**Comment by thinkbulecount2** [comment]
@NateWr Tried it but it breaks the whole theme, so commenting out one by one to see what's breaking what.

**Comment by Vitaliy-1** [comment]
Yeah, Health Sciences uses different variables. But I would also consider disabling autocomplete feature as we don't use it. Theoretically, this should remove redundant elements and `no search results` notice.

**Comment by thinkbulecount2** [comment]
@Vitaliy-1 I made some changes... do you mind checking it out?

**Comment by Vitaliy-1** [comment]
@thinkbulecount2,

Can you compare this approach with the one I've introduced for Pragma: https://github.com/pkp/pragma/commit/a555c8111533240c1d24d5fba5d358a0c7a24ae3. I disabled autocomplete there on JS level, rather than making CSS changes.

**Comment by thinkbulecount2** [comment]
@Vitaliy-1 Oh so this is why Pragma (and Immersion?) do not have the same issue? If that's the case I'll revert to a JS change so that they are all consistent.

**Comment by thinkbulecount2** [comment]
@Vitaliy-1 Made the change! Please peruse at your convenience. :)

**Comment by Vitaliy-1** [comment]
Many Thanks!

**Comment by Vitaliy-1** [comment]
Not sure if it's because of this fix but anywhere it works :)

**Pull request merged**
