### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by kant**
Spanish translation of the Health Sciences theme for OJS

### CODE REVIEW

**Comment by marcbria** [comment]
Sorry for the silence. I'm on vacations.

I will take a look to this tonight.

Take care,
m.

El 3 de agosto de 2018 11:19:18 CEST, Nate Wright <notifications@github.com> escribió:
>@marcbria can you take a look at this and let us know if it's good to
>merge?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pkp/healthSciences/pull/103#issuecomment-410196778

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by marcbria** [comment]
The translation is good, but it can be improved.
I can't edit the PR so I comment with the changes.
Please Nate, do you mind to replace the chain before merging?

Thanks @kant for the contribution.

**Comment by NateWr** [comment]
Thanks @marcbria! Sorry to bother you on your vacation.

@kant can you push a new commit with the recommended change from Marc?

**Comment by NateWr** [comment]
@kant just following up on this. Are you able to make the change recommended by Marc?

**Comment by kant** [comment]
@NateWr I am on the way, Nate

**Comment by marcbria** [comment]
Great. Thanks @kant for your work.

**Comment by NateWr** [comment]
:+1: Thanks everyone!

**Pull request merged**
